import getSession from "@/actions/getSession";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import Sidenav from "./_components/Sidenav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  if (!session?.user) return redirect("/");
  return (
    <div>
      <Sidenav />
      {children}
    </div>
  );
}
