import getSession from "@/actions/getSession";
import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import Sidenav from "./_components/Sidenav";
import { GetBucketsbyUserID, ValidateBucketOwnership } from "@/actions/Buckets";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { bucketId: string };
}>) {
  const session = await getSession();

  if (!session?.user) return redirect("/");
  const userId = parseInt(session?.user.id as string);
  const bucketId = parseInt(params.bucketId as string);
  const auth = await ValidateBucketOwnership(userId, bucketId);

  if (!auth) notFound();

  return (
    <div className="flex px-24 gap-16 pt-6">
      <Sidenav bucketId={parseInt(params.bucketId)} />
      <main className="grow">{children}</main>
    </div>
  );
}
